### PR TITLE
Standardize the cached Constraint results to match action results

### LINKED ISSUE #1150: Schema Mismatch Between Cached Constraint Run and Action Response
The cached results in the `constraint_run` table stores the names of the used resources under "resourceNames". The response from the Constraints action stores them under "resourceIds"

Additionally in the `violations`part of results, the violating windows are stored as `windows` in the action response and as `violationWindows` in the cached results

Also, `type` in the response vs `constraintType` in the cache

### PR DESCRIPTION
**Pull request by Mythicaeda**
* **Tickets addressed:** Closes #1150
* **Review:** By commit  
* **Merge strategy:** Merge (no squash)  

## Description

Updated the parser for constraint violations so that the cached run has the same key names as the action response.

## Verification

Wrote a JSON parser while working on #1057 that successfully parses both the `checkConstraints` action response and the cached values from `constraint_run`.

## Documentation

No docs were invalidated

## Future work

None

### CODE REVIEW

**Comment by JoelCourtney** [comment]
@jeffpamer FYI this will impact your UI code

**Review by JoelCourtney — APPROVED** [review]

**Comment by JoelCourtney** [comment]
Don't merge until the UI has a PR to keep up to date

**Comment by jeffpamer** [comment]
Looks like this should be a pretty small change on our end if I'm interpreting this correctly. I'll try to get a UI PR up this afternoon or first thing tomorrow.

**Comment by jeffpamer** [comment]
Upon further investigation this does not appear to be a breaking change for the UI as we are currently not reading anything out of `constraint_run`. If we do start using the cached run results in the future, it looks like after this change the schema will match the shape we are already expecting for constraint check results.

**Pull request merged**
