### PR TITLE
AERIE-1609 Adding foo-missionmodel package to Github

### PR DESCRIPTION
**Pull request by goetzrrGit**
* **Tickets addressed:** AERIE-1609
* **Review:** By commit  
* **Merge strategy:** Merge (no squash)  

## Description
Since going public, we are using Github actions to push packages to Github. We already added the banananation model to Github packages. This ticket is to include the other mission models. The only other one located in this project is foo-missionmodel

## Verification
I am unable to test this because I need this branch merged in for the Github action to be ran. This might require multiple attempts....

## Documentation
None

## Future work
Verify that the foo-missionmodel package is generated upon merge

### CODE REVIEW

**Comment by camargo** [comment]
Was there a reason we did not include this in the deployed packages before?

**Comment by goetzrrGit** [comment]
@camargo I am not sure, I just had a ticket to include other models and I noticed this one wasn't included. I am not sure if we need this model anymore?

@patkenneally do you have any insight on this? Do we need this model anymore?

**Comment by patkenneally** [comment]
We do want foo-missionmodel, but we may not want to publish the jar if it turns out there is no need. Am I right to assume you are using only Banananation for the tests you're developing? If yes we only need publish to artifactory Banananation.

**Comment by goetzrrGit** [comment]
@patkenneally and @camargo I will close this PR because I am only using the bananation.jar for the test.

**Pull request closed without merging**
