### PR TITLE
test: add ui health check

### PR DESCRIPTION
**Pull request by camargo**
## Description

Adds an e2e test that checks the UI server health

### CODE REVIEW

**Review by dyst5422 — APPROVED** [review]
This isn't directly related to this PR, but why did you make the mission model type global instead of simply importing it where necessary?

**Comment by camargo** [comment]
@dyst5422 Just for convenience. Since the types are not really part of a specific library it just reduces the boilerplate needed to use what's in the `types` directory.

**Comment by dyst5422** [comment]
> @dyst5422 Just for convenience. Since the types are not really part of a specific library it just reduces the boilerplate needed to use what's in the `types` directory.

I don't REALLY care, but just as devils advocate... I'd say that polluting the global namespace for type checking is nearly as bad as at runtime and should only really be used for extending built-ins/globalThis.

**Comment by camargo** [comment]
@dyst5422 Yeah I used to think this way. I think app-specific types are safe for global use across an application and you don't gain much extra safety from using them in modules since they are compiled away anyway. Any collisions can be addressed with a type namespace, and there is less overall syntax to use them. You avoid really long import statements of different types, or just using * to import all the types into a variable anyway.

**Review by mattdailis — APPROVED** [review]

**Comment by dyst5422** [comment]
> @dyst5422 Yeah I used to think this way. I think app-specific types are safe for global use across an application and you don't gain much extra safety from using them in modules since they are compiled away anyway. Any collisions can be addressed with a type namespace, and there is less overall syntax to use them. You avoid really long import statements of different types, or just using * to import all the types into a variable anyway.

I'll let you convince me as we go 😃

**Pull request merged**
