### PR TITLE
[FIX] Add Spice library for Mac M1/arm64 architectures

### PR DESCRIPTION
**Pull request by adrienmaillard**
* **Tickets addressed:** None
* **Review:** By commit  
* **Merge strategy:** Merge (no squash)  

## Description

After transitioning to a new M1 MBP, `SpiceTests` was failing. NAIF does not distribute a libJNISpice for M1 architectures. I re-compiled the library locally and updated the `SpiceLoader` to load the appropriate library according to the architecture detected.  

## Verification

The test now passes. If you have an M1 mac, please tell me if this works.

## Documentation

I am not aware of documentation about Spice. 

## Future work

Ask NAIF to provide a proper distribution ?

### CODE REVIEW

**Comment by Twisol** [comment]
> NAIF does not distribute a libJNISpice for M1 architectures

I'm not sure JNISpice is even an official product of NAIF, actually...

**Comment by adrienmaillard** [comment]
> I'm not sure JNISpice is even an official product of NAIF, actually...

They mention it on https://naif.jpl.nasa.gov/naif/toolkit.html and provide several versions on https://naif.jpl.nasa.gov/pub/naif/misc/JNISpice_N0067/ 
In alpha-test, okay...

**Comment by Twisol** [comment]
Ah, interesting. Maybe it's a recent development -- I recall there was some consternation in the last couple years about JNISpice not being an officially supported product. Well, it's *really* good that that's being rectified :)

**Comment by adrienmaillard** [comment]
Closing this PR to be replaced by https://github.com/NASA-AMMOS/aerie/pull/271.

**Pull request closed without merging**
