### PR TITLE
Remove {POSTGRES_DB} enviornment variable

### PR DESCRIPTION
**Pull request by Mythicaeda**
* **Tickets addressed:** Hotfix
* **Review:** By commit  
* **Merge strategy:** Merge (no squash)  

## Description

Removed the POSTGRES_DB environment variable, as it doesn't need to be a secret.

## Verification

Composed the project and ran `./gradlew test`.

## Documentation

Removed mention of the POSTGRES_DB environment variable from the README and .env.template.

### CODE REVIEW

**Comment by JoelCourtney** [comment]
Actually, it seems weird to me to make the db name configurable, especially since it affects the container name. What was the rationale behind making this configurable?

I think it would be better to put only the username and password in `.env`, because the db name is not a secret.

**Comment by goetzrrGit** [comment]
It is a good idea, but I agree with Joel, I feel like having the container name in a .env is more trouble than it is worth. I don't think there is a need to keep the DB name a secret for security reasons, but I could be wrong.

**Comment by Mythicaeda** [comment]
I've modified the PR so `POSTGRES_DB` is no longer in the `.env` @JoelCourtney and @goetzrrGit

**Review by goetzrrGit — APPROVED** [review]
Looks good to me.

**Comment by skovati** [comment]
FYI @Mythicaeda, you can apply the `hotfix` label to reduce required approvals to one ;)

**Review by skovati — APPROVED** [review]
That being said, LGTM

**Pull request merged**
