### PR TITLE
[HOTFIX] Fix bad npm registry

### PR DESCRIPTION
**Pull request by dyst5422**
* **Tickets addressed:** HOTFIX
* **Review:** By commit  
* **Merge strategy:** Merge (no squash)  

## Description

When I updated the user code runner, my npm registry was set to JPL artifactory, so that got encoded into the package-lock files. This fixes that blunder.

Also locks version for typescript-json-schema to work around a dependency error with the 0.53.1 version

### CODE REVIEW

**Review by goetzrrGit — COMMENTED** [review]
These files were deleted but don't we want to create new lock files?

**Comment by dyst5422** [comment]
> These files were deleted but don't we want to create new lock files?

🤦 ~amended the commit~ - ~ugh why is this such a PITA, gimme a sec~ - THERE WE GO

**Review by goetzrrGit — COMMENTED** [review]
That looks better :D One more question what about the command-expansion-server lock file? Was that one not messed up?

**Comment by dyst5422** [comment]
This has turned into a dependency nightmare. I think I've got it right this time.

**Comment by dyst5422** [comment]
> That looks better :D One more question what about the command-expansion-server lock file? Was that one not messed up?

Great question. I have no idea. It's clearly right here https://github.com/NASA-AMMOS/aerie/blob/hotfix/bad-npm-source/command-expansion-server/package-lock.json#L1046

Perhaps I had already installed the 0.3.1 locally on a different day when my registry was correctly set and so the package-lock didn't change.

**Comment by dyst5422** [comment]
@goetzrrGit finally got it

**Review by skovati — APPROVED** [review]
🥵

**Review by goetzrrGit — APPROVED** [review]
Merge, Merge, Merge

**Pull request merged**
