### PR TITLE
[AERIE-1606]  dataset trigger tests

### PR DESCRIPTION
**Pull request by dyst5422**
* **Tickets addressed:** AERIE-1606
* **Review:** By commit
* **Merge strategy:** Merge (no squash)

## Description
Adds tests for dataset triggers. Builds on work in #26 

## Verification
Inspection

## Documentation
None - tests added

## Future work
None (hopefully)

### CODE REVIEW

**Comment by goetzrrGit** [comment]
I can't seem to run these tests? It says ignoring 13 test. Am I doing this right

Screen Shot 2022-01-13 at 8 27 55 AM

Screen Shot 2022-01-13 at 8 28 34 AM

**Review by goetzrrGit — COMMENTED** [review]
Looks good to me. Let me know how to test this before approving?

**Comment by dyst5422** [comment]
> Looks good to me. Let me know how to test this before approving?

It will skip the tests if it cant connect to a postgres instance. So make sure you have one deployed locally (or via docker) at `localhost:5432`

**Review by goetzrrGit — APPROVED** [review]
Looks good and all the tests pass. Thank you for the help running them.

**Comment by pcrosemurgy** [comment]
Seems like this PR is based off of changes made in #26, right? If so, to make the diffstat minimal you could change the base branch to the branch in #26 for now.

**Comment by dyst5422** [comment]
@kroffo You're up for a quick PR review

**Review by pcrosemurgy — APPROVED** [review]
Looks good, only comment I have is that you could possibly refactor the repeated `try` blocks into a method to save some boilerplate.

**Pull request merged**
