### PR TITLE
Add docs page on temporal subset scheduling

### PR DESCRIPTION
**Pull request by mattdailis**
* **Tickets addressed:** N/A
* **Review:** By commit  
* **Merge strategy:** Merge (no squash)  

## Documentation

This PR adds a page on temporal subset scheduling - it's a special case of Global Scheduling Conditions, but that may not be immediately obvious, so it's worth calling out explicitly.

## Verification
I ran `make preview` and it looked okay - we'll see if the PR action checks are happy with my links.

## Future work

None

### CODE REVIEW

**Review by camargo — APPROVED** [review]

**Review by Mythicaeda — APPROVED** [review]
LGTM! Links are good as well. For future reference, we don't run the linkchecker for external links as a PR step due to the fact that it always fails (it detects and then fails to connect to a plaintext link to `localhost` found in the documentation on contributing to the docs). Instead see [here](https://nasa-ammos.github.io/aerie/develop/contribute/documentation/docs-pr.html#previewing-local-changes) for how to check links.

**Comment by mattdailis** [comment]
> LGTM! Links are good as well. For future reference, we don't run the linkchecker for external links as a PR step due to the fact that it always fails (it detects and then fails to connect to a plaintext link to `localhost` found in the documentation on contributing to the docs). Instead see [here](https://nasa-ammos.github.io/aerie/develop/contribute/documentation/docs-pr.html#previewing-local-changes) for how to check links.

Thanks @Mythicaeda - I'll go try to do a linkcheck of my own for practice now.

**Comment by Mythicaeda** [comment]
> Thanks @Mythicaeda - I'll go try to do a linkcheck of my own for practice now.

Alright! Also, I forgot to mention it in my approval, but the current list of known linkcheck errors (and why they occur) can be found in [this PR](https://github.com/NASA-AMMOS/aerie/pull/486).

**Comment by mattdailis** [comment]
Hmm, I got some broken links:

```
(user-guide/upgrade-guides/0-13-2-to-1-0-0: line  161) broken    https://github.com/NASA-AMMOS/aerie/blob/develop/deployment/Environment.md#aerie-scheduler-worker - Anchor 'aerie-scheduler-worker' not found
(user-guide/upgrade-guides/0-13-2-to-1-0-0: line  161) broken    https://github.com/NASA-AMMOS/aerie/blob/develop/deployment/Environment.md#aerie-scheduler - Anchor 'aerie-scheduler' not found
```

Any tips on what I might have done wrong? 

EDIT: Whoops, just saw your message, looks like they're in that list!

**Pull request merged**
