### PR TITLE
build: upgrade command expansion server deps

### PR DESCRIPTION
**Pull request by camargo**
## Description

- Also reorder scripts
- Cleanup package.json
- Update temporal serializer type

### CODE REVIEW

**Review by dyst5422 — APPROVED** [review]
All changes make sense to me. I am still working on double checking things locally, will update this comment once I've completed that.

**Review by dyst5422 — APPROVED** [review]
All changes make sense to me. Tested on my computer and the changes to the test snapshots are good.

**Review by mattdailis — APPROVED** [review]
Approving because Dylan approved - I'm not sure I follow why all those double backslashes were removed in the snapshot.

**Comment by dyst5422** [comment]
> Approving because Dylan approved - I'm not sure I follow why all those double backslashes were removed in the snapshot.

I understand why the expectation is that they shouldn't be there. What I don't understand is how they got there in the first place.

**Pull request merged**
