### PR TITLE
[AERIE-1908] Jetty-Hasura idle timeout clash

### PR DESCRIPTION
**Pull request by adrienmaillard**
* **Tickets addressed:** AERIE-1908
* **Review:** By commit  
* **Merge strategy:** Merge (no squash)  

## Description

Hasura keeps connections open to a default of 180 seconds to re-use them. But the default HTTP idle timeout of jetty is 30 seconds so it will close the connection early and display a stack trace in the logs of `merlin-server` and `scheduler-server`.

Note that the stack trace is not an error but the normal way Jetty is processing idle timeouts. The stack trace is printed as a debug message and the exception is not even thrown but passed.  

What would it take to change the idle timeout of jetty servers in both the `scheduler-server` and `merlin-server` ? I found only one way of doing so.
I could not find a way of configuring HTTP idle timeouts of the inner server of jetty. Websockets idle timeouts can be configured but not HTTP idle timeouts.
 
So, we replace the server that Jetty is creating by default by a jetty server that we can configure beforehand.

Remarks/questions : 
- After doing this, the timeout is effectively 180s, I have not seen other differences in how the scheduler behaves but I am not sure the inner server is totally equivalent.  I have compared the `Server` objects by hand and they **seem** to be the same but I do not see how to confirm.  
- Would there be another way of configuring idle timeouts? 

## Verification

I researched/tested this by using the goal editor in `aerie-ui`. No new tests.

## Documentation

None

## Future work

Fix the following that I keep seeing in logs 
```
[main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable
java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @7f1dd5e7
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:394)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:353)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:344)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:294)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:93)
	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:287)
	at io.netty.channel.epoll.Native.<clinit>(Native.java:70)
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39)
	at com.impossibl.postgres.protocol.v30.ServerConnectionFactory.createInetSocketChannel(ServerConnectionFactory.java:298)
	at com.impossibl.postgres.protocol.v30.ServerConnectionFactory.createChannel(ServerConnectionFactory.java:259)
	at com.impossibl.postgres.protocol.v30.ServerConnectionFactory.connect(ServerConnectionFactory.java:150)
	at com.impossibl.postgres.protocol.v30.ServerConnectionFactory.connect(ServerConnectionFactory.java:143)
	at com.impossibl.postgres.protocol.v30.ServerConnectionFactory.connect(ServerConnectionFactory.java:124)
	at com.impossibl.postgres.system.BasicContext.<init>(BasicContext.java:213)
	at com.impossibl.postgres.jdbc.PGDirectConnection.<init>(PGDirectConnection.java:236)
	at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:317)
	at com.impossibl.postgres.jdbc.AbstractDataSource.createConnection(AbstractDataSource.java:125)
	at com.impossibl.postgres.jdbc.PGDataSource.getConnection(PGDataSource.java:71)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at gov.nasa.jpl.aerie.scheduler.server.SchedulerAppDriver.loadStores(SchedulerAppDriver.java:142)
	at gov.nasa.jpl.aerie.scheduler.server.SchedulerAppDriver.main(SchedulerAppDriver.java:76)

```

### CODE REVIEW

**Comment by mattdailis** [comment]
I think you're right - creating your own jetty server object does seem like the preferred way to set jetty configurations.

Is the error you mention in your future work section pre-existing, or is it introduced by this PR?

**Comment by adrienmaillard** [comment]
> I think you're right - creating your own jetty server object does seem like the preferred way to set jetty configurations.
> 
> Is the error you mention in your future work section pre-existing, or is it introduced by this PR?

The error is pre-existing.

**Review by mattdailis — APPROVED** [review]

**Comment by patkenneally** [comment]
@adrienmaillard what aspects of the Jetty Server in the Scheduler are you thinking are not the same after your change? 

It may be the same as what you already did by hand, but would something like the Jetty dump functionality help confirm that the Servers are the same (expect for your change)? 

[Jetty server config - dump settings](https://www.eclipse.org/jetty/documentation/jetty-11/operations-guide/index.html#og-module-server-config)

**Review by patkenneally — APPROVED** [review]
Pending the settings dump inspection.

**Comment by adrienmaillard** [comment]
I have dumped the conf jetty configurations and after some rearranging of the files, here is the diff I am getting 
[Dump diff](https://github.com/NASA-AMMOS/aerie/files/9213403/compare_jetty.html.zip)

~~Left is with the "custom" jetty server that this PR proposes. Right is with the original jetty that javalin is creating.~~ 
Right is with the "custom" jetty server that this PR proposes. Left is with the original jetty that javalin is creating.

I do not see major differences but 
- the presence of an `AttributeContainerMap` in the custom one
- the `sendServerVersion` has a different value 
- one parameter is 200 in one, 250 in the other.

**Comment by patkenneally** [comment]
Interestingly the Javalin FAQ says that it servers with a `QueuedThreadPool` size of 250 yet as you've shown it's only 200.

**Comment by adrienmaillard** [comment]
> Interestingly the Javalin FAQ says that it servers with a `QueuedThreadPool` size of 250 yet as you've shown it's only 200.

Yeah, it's because I've reversed which is which... Left is the jetty javalin and right is the custom one.

**Comment by adrienmaillard** [comment]
We can actually set the `ThreadPool` ourselves with max size 250 if we want. After doing that, this discrepancy is gone. The really weird thing is that the `idleTimeout` appears to be -1 in both cases when we know it is not the case. So there are hidden parameters we do not see in these dumps.

**Pull request merged**
