### PR TITLE
[AERIE-1856] normalize dsl return types

### PR DESCRIPTION
**Pull request by dyst5422**
* **Tickets addressed:** AERIE-1856
* **Review:** By commit  
* **Merge strategy:** Merge (no squash)  

## Description

Normalize our return type for typescript files.
## Verification

Added tests to command expansion for this.

## Documentation

Need to update the wiki on pulling these files

## Future work

None

### CODE REVIEW

**Review by goetzrrGit — COMMENTED** [review]
I am sure you are aware but the new test are not working, you might want to bring this https://github.com/NASA-AMMOS/aerie/pull/202 into this PR when it is merged.

**Review by patkenneally — CHANGES_REQUESTED** [review]
I've reviewed the PR and all looks good. Let me know when the wiki is updated and I'll add an approval.

**Comment by camargo** [comment]
After this is merged I can quickly update the UI today to account for the change

**Review by goetzrrGit — APPROVED** [review]

**Comment by goetzrrGit** [comment]
@patkenneally Dylan might be out today and I don't want this to block @camargo 

I have updated the wiki with the changes to this PR:

https://github.com/NASA-AMMOS/aerie/wiki/Upload-and-Generate-Command_Library-File
https://github.com/NASA-AMMOS/aerie/wiki/Generate-Activity_Type-library

**Review by patkenneally — APPROVED** [review]

**Pull request merged**
