### PR TITLE
[AERIE 2053] Add Sphinx Documentation Generation and Publishing

### PR DESCRIPTION
**Pull request by patkenneally**
I'm testing some the sphinx actions workflows. And need a PR with which I can trigger them.

### CODE REVIEW

**Comment by camargo** [comment]
Can we add a link to the new documentation site on `gh-pages` from the repos top-level `README.md`?

**Comment by Mythicaeda** [comment]
That's the plan as soon as this is up and the new site is deployed!

**Comment by camargo** [comment]
Can we add some instructions for how to test this locally?

**Review by mattdailis — APPROVED** [review]

**Review by skovati — APPROVED** [review]
LGTM! Nice work on this. My only concern is storing those PNGs as git objects in the develop branch, but that seems hard to avoid unless we adopt something like [git LFS](https://git-lfs.github.com/)

**Comment by Mythicaeda** [comment]
@camargo I've added the local build instructions to the docs. For a quick reference out here, however, the instructions are:

* Install [Python 3.7](https://www.python.org/downloads/) or later.
* Install [Poetry 1.12](https://python-poetry.org/docs/master/) or later.
* Run `make preview` from the `docs` directory to view changes to the site as you work (It will be hosted at http://127.0.0.1:5500/)
* Run `make dirhtml` to ensure that the site will deploy.
* Run `make clean` to clean files between builds.

**Comment by camargo** [comment]
I got an error when initially installing Poetry (not important but it was because my local PIP was pointing to Artifactory). The failure wrote a log file `poetry-installer-error-_ih5ur0n.log`. Can we add `*.log` to Aerie top-level `.gitignore`?

**Comment by camargo** [comment]
Also probably for a future PR but the search results seem to still point to the `scylladb` docs. Is this easy to change?

**Review by camargo — APPROVED** [review]
LGTM! Left some clean up comments. Overall works locally and looks great.

**Pull request merged**
